/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../build/components/body/progress-bar.component';
const styles_ProgressBarComponent:any[] = ([] as any[]);
export const RenderType_ProgressBarComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProgressBarComponent,
  data: {}
}
);
export function View_ProgressBarComponent_0(log:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,[
    (log()(),import0.ɵted((null as any),['\n    '])),
    (log()(),import0.ɵeld(0,(null as any),(null as any),6,'div',[
      [
        'class',
        'progress-linear'
      ]
      ,
      [
        'role',
        'progressbar'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (log()(),import0.ɵted((null as any),['\n      '])),
      (log()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (log()(),import0.ɵted((null as any),['\n        '])),
      (log()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'bar'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (log()(),import0.ɵted((null as any),['\n      '])),
    (log()(),import0.ɵted((null as any),['\n    '])),
    (log()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(check,view) => {
    check(view,1,0);
    check(view,3,0);
    check(view,5,0);
  });
}
function View_ProgressBarComponent_Host_0(log:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (log()(),import0.ɵeld(0,(null as any),(null as any),1,'datatable-progress',([] as any[]),(null as any),(null as any),(null as any),View_ProgressBarComponent_0,RenderType_ProgressBarComponent)),
    (log()(),import0.ɵdid(24576,(null as any),0,import1.ProgressBarComponent,([] as any[]),(null as any),(null as any)))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(check,view) => {
    check(view,0,0);
  });
}
export const ProgressBarComponentNgFactory:import0.ComponentFactory<import1.ProgressBarComponent> = import0.ɵccf('datatable-progress',import1.ProgressBarComponent,View_ProgressBarComponent_Host_0);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3RlbXAvbmd4LWRhdGF0YWJsZS9uZ3gtZGF0YXRhYmxlLmZvcmsvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovZGV2L3RlbXAvbmd4LWRhdGF0YWJsZS9uZ3gtZGF0YXRhYmxlLmZvcmsvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQudHMiLCJuZzovLy9DOi9kZXYvdGVtcC9uZ3gtZGF0YXRhYmxlL25neC1kYXRhdGFibGUuZm9yay9idWlsZC9jb21wb25lbnRzL2JvZHkvcHJvZ3Jlc3MtYmFyLmNvbXBvbmVudC50cy5Qcm9ncmVzc0JhckNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovZGV2L3RlbXAvbmd4LWRhdGF0YWJsZS9uZ3gtZGF0YXRhYmxlLmZvcmsvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQudHMuUHJvZ3Jlc3NCYXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbbnVsbCwiXG4gICAgPGRpdiBjbGFzcz1cInByb2dyZXNzLWxpbmVhclwiIHJvbGU9XCJwcm9ncmVzc2JhclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmFyXCI+PC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgIiwiPGRhdGF0YWJsZS1wcm9ncmVzcz48L2RhdGF0YWJsZS1wcm9ncmVzcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDSTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBZ0Q7TUFDOUM7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtNQUNyQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXVCO0lBQ25CO0lBQ0Y7OztJQUpOO0lBQ0U7SUFDRTs7Ozs7SUNIUjtJQUFBOzs7SUFBQTs7SUFBQTs7OyJ9
