/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../build/components/body/selection.component';
const styles_DataTableSelectionComponent:any[] = ([] as any[]);
export const RenderType_DataTableSelectionComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DataTableSelectionComponent,
  data: {}
}
);
export function View_DataTableSelectionComponent_0(log:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (log()(),import0.ɵted((null as any),['\n    '])),
    (log()(),import0.ɵncd((null as any),0)),
    (log()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_DataTableSelectionComponent_Host_0(log:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (log()(),import0.ɵeld(0,(null as any),(null as any),1,'datatable-selection',([] as any[]),(null as any),(null as any),(null as any),View_DataTableSelectionComponent_0,RenderType_DataTableSelectionComponent)),
    (log()(),import0.ɵdid(24576,(null as any),0,import1.DataTableSelectionComponent,([] as any[]),(null as any),(null as any)))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(check,view) => {
    check(view,0,0);
  });
}
export const DataTableSelectionComponentNgFactory:import0.ComponentFactory<import1.DataTableSelectionComponent> = import0.ɵccf('datatable-selection',import1.DataTableSelectionComponent,View_DataTableSelectionComponent_Host_0);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3RlbXAvbmd4LWRhdGF0YWJsZS9uZ3gtZGF0YXRhYmxlLmZvcmsvYnVpbGQvY29tcG9uZW50cy9ib2R5L3NlbGVjdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovZGV2L3RlbXAvbmd4LWRhdGF0YWJsZS9uZ3gtZGF0YXRhYmxlLmZvcmsvYnVpbGQvY29tcG9uZW50cy9ib2R5L3NlbGVjdGlvbi5jb21wb25lbnQudHMiLCJuZzovLy9DOi9kZXYvdGVtcC9uZ3gtZGF0YXRhYmxlL25neC1kYXRhdGFibGUuZm9yay9idWlsZC9jb21wb25lbnRzL2JvZHkvc2VsZWN0aW9uLmNvbXBvbmVudC50cy5EYXRhVGFibGVTZWxlY3Rpb25Db21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L2Rldi90ZW1wL25neC1kYXRhdGFibGUvbmd4LWRhdGF0YWJsZS5mb3JrL2J1aWxkL2NvbXBvbmVudHMvYm9keS9zZWxlY3Rpb24uY29tcG9uZW50LnRzLkRhdGFUYWJsZVNlbGVjdGlvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOltudWxsLCJcbiAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICIsIjxkYXRhdGFibGUtc2VsZWN0aW9uPjwvZGF0YXRhYmxlLXNlbGVjdGlvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDSTtJQUF5Qjs7Ozs7O0lDRDdCO0lBQUE7OztJQUFBOztJQUFBOzs7In0=
